kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongosh2-1 
  annotations:
    volume.beta.kubernetes.io/storage-class: repl-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
