apiVersion: v1
kind: Service
metadata:
  name: mongocfg1
  labels:
    app: mongocfg1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongocfg1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongocfg1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongocfg1
  template:
    metadata:
      labels:
        app: mongocfg1
    spec:
      restartPolicy: Always
      hostname: mongocfg1
      containers:
      - image: mongo:latest
        name: mongocfg1
        ports:
        - name: mongocfg1
          containerPort: 27017
        volumeMounts:
            - name: mongocfg1
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--configsvr", "--replSet", "cfgrs", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--bind_ip_all", "--port", "27017"]
      volumes:
        - name: mongocfg1
          persistentVolumeClaim:
           claimName: mongocfg1
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: mongocfg2
  labels:
    app: mongocfg2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongocfg2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongocfg2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongocfg2
  template:
    metadata:
      labels:
        app: mongocfg2
    spec:
      restartPolicy: Always
      hostname: mongocfg2
      containers:
      - image: mongo:latest
        name: mongocfg2
        ports:
        - name: mongocfg2
          containerPort: 27017
        volumeMounts:
            - name: mongocfg2
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--configsvr", "--replSet", "cfgrs", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--bind_ip_all", "--port", "27017"]
      volumes:
        - name: mongocfg2
          persistentVolumeClaim:
           claimName: mongocfg2
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: mongocfg3
  labels:
    app: mongocfg3
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongocfg3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongocfg3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongocfg3
  template:
    metadata:
      labels:
        app: mongocfg3
    spec:
      restartPolicy: Always
      hostname: mongocfg3
      containers:
      - image: mongo:latest
        name: mongocfg3
        ports:
        - name: mongocfg3
          containerPort: 27017
        volumeMounts:
            - name: mongocfg3
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--configsvr", "--replSet", "cfgrs", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--bind_ip_all", "--port", "27017"]
      volumes:
        - name: mongocfg3
          persistentVolumeClaim:
           claimName: mongocfg3
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
