apiVersion: v1
kind: Service
metadata:
  name: mongos1
  labels:
    app: mongos1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongos1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos1
  template:
    metadata:
      labels:
        app: mongos1
    spec:
      restartPolicy: Always
      hostname: mongos1
      containers:
      - image: mongo:latest
        name: mongos1
        ports:
        - name: mongos1
          containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
            - name: mongos1
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongos"]
        args: ["--configdb", "cfgrs/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017", "--keyFile", "/etc/secrets-volume/mongosecret", "--bind_ip_all"]
      volumes:
        - name: mongos1
          persistentVolumeClaim:
           claimName: mongos1
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: mongos2
  labels:
    app: mongos2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongos2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos2
  template:
    metadata:
      labels:
        app: mongos2
    spec:
      restartPolicy: Always
      hostname: mongos2
      containers:
      - image: mongo:latest
        name: mongos2
        ports:
        - name: mongos2
          containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
            - name: mongos2
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongos"]
        args: ["--configdb", "cfgrs/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017", "--keyFile", "/etc/secrets-volume/mongosecret", "--bind_ip_all"]
      volumes:
        - name: mongos2
          persistentVolumeClaim:
           claimName: mongos2
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
