# Mongo shard replica set 2 node 1
apiVersion: v1
kind: Service
metadata:
  name: mongosh2-1
  labels:
    app: mongosh2-1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh2-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh2-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh2-1
  template:
    metadata:
      labels:
        app: mongosh2-1
    spec:
      restartPolicy: Always
      hostname: mongosh2-1
      containers:
      - image: mongo:latest
        name: mongosh2-1
        ports:
        - name: mongosh2-1
          containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        volumeMounts:
            - name: mongosh2-1
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs2", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh2-1
          persistentVolumeClaim:
           claimName: mongosh2-1
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
# Mongo shard replica set 2 node 2
apiVersion: v1
kind: Service
metadata:
  name: mongosh2-2
  labels:
    app: mongosh2-2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh2-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh2-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh2-2
  template:
    metadata:
      labels:
        app: mongosh2-2
    spec:
      restartPolicy: Always
      hostname: mongosh2-2
      containers:
      - image: mongo:latest
        name: mongosh2-2
        ports:
        - name: mongosh2-2
          containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        volumeMounts:
            - name: mongosh2-2
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs2", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh2-2
          persistentVolumeClaim:
           claimName: mongosh2-2
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256

---
# Mongo shard replica set 2 node 3
apiVersion: v1
kind: Service
metadata:
  name: mongosh2-3
  labels:
    app: mongosh2-3
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh2-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh2-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh2-3
  template:
    metadata:
      labels:
        app: mongosh2-3
    spec:
      restartPolicy: Always
      hostname: mongosh2-3
      containers:
      - image: mongo:latest
        name: mongosh2-3
        ports:
        - name: mongosh2-3
          containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        volumeMounts:
            - name: mongosh2-3
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs2", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh2-3
          persistentVolumeClaim:
           claimName: mongosh2-3
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256