# Mongo shard replica set 3 node 1
apiVersion: v1
kind: Service
metadata:
  name: mongosh3-1
  labels:
    app: mongosh3-1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh3-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh3-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh3-1
  template:
    metadata:
      labels:
        app: mongosh3-1
    spec:
      restartPolicy: Always
      hostname: mongosh3-1
      containers:
      - image: mongo:latest
        name: mongosh3-1
        ports:
        - name: mongosh3-1
          containerPort: 27017
        volumeMounts:
            - name: mongosh3-1
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs3", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh3-1
          persistentVolumeClaim:
           claimName: mongosh3-1
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
# Mongo shard replica set 3 node 2
apiVersion: v1
kind: Service
metadata:
  name: mongosh3-2
  labels:
    app: mongosh3-2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh3-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh3-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh3-2
  template:
    metadata:
      labels:
        app: mongosh3-2
    spec:
      restartPolicy: Always
      hostname: mongosh3-2
      containers:
      - image: mongo:latest
        name: mongosh3-2
        ports:
        - name: mongosh3-2
          containerPort: 27017
        volumeMounts:
            - name: mongosh3-2
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs3", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh3-2
          persistentVolumeClaim:
           claimName: mongosh3-2
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
# Mongo shard replica set 3 node 3
apiVersion: v1
kind: Service
metadata:
  name: mongosh3-3
  labels:
    app: mongosh3-3
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh3-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh3-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh3-3
  template:
    metadata:
      labels:
        app: mongosh3-3
    spec:
      restartPolicy: Always
      hostname: mongosh3-3
      containers:
      - image: mongo:latest
        name: mongosh3-3
        ports:
        - name: mongosh3-3
          containerPort: 27017
        volumeMounts:
            - name: mongosh3-3
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs3", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh3-3
          persistentVolumeClaim:
           claimName: mongosh3-3
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256