# Mongo shard replica set 4 node 1
apiVersion: v1
kind: Service
metadata:
  name: mongosh4-1
  labels:
    app: mongosh4-1
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh4-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh4-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh4-1
  template:
    metadata:
      labels:
        app: mongosh4-1
    spec:
      restartPolicy: Always
      hostname: mongosh4-1
      containers:
      - image: mongo:latest
        name: mongosh4-1
        ports:
        - name: mongosh4-1
          containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        volumeMounts:
            - name: mongosh4-1
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs4", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh4-1
          persistentVolumeClaim:
           claimName: mongosh4-1
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
# Mongo shard replica set 4 node 2
apiVersion: v1
kind: Service
metadata:
  name: mongosh4-2
  labels:
    app: mongosh4-2
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh4-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh4-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh4-2
  template:
    metadata:
      labels:
        app: mongosh4-2
    spec:
      restartPolicy: Always
      hostname: mongosh4-2
      containers:
      - image: mongo:latest
        name: mongosh4-2
        ports:
        - name: mongosh4-2
          containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        volumeMounts:
            - name: mongosh4-2
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--shardsvr", "--replSet", "rs4", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh4-2
          persistentVolumeClaim:
           claimName: mongosh4-2
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
---
# Mongo shard replica set 4 node 3
apiVersion: v1
kind: Service
metadata:
  name: mongosh4-3
  labels:
    app: mongosh4-3
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongosh4-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongosh4-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongosh4-3
  template:
    metadata:
      labels:
        app: mongosh4-3
    spec:
      restartPolicy: Always
      hostname: mongosh4-3
      containers:
      - image: mongo:latest
        name: mongosh4-3
        ports:
        - name: mongosh4-3
          containerPort: 27017
        resources:
          requests:
            memory: "512Mi"
            cpu: "400m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        volumeMounts:
            - name: mongosh4-3
              mountPath: /data/db
            - name: secrets-volume
              mountPath: /etc/secrets-volume/mongosecret
              subPath: mongosecret
        command: ["mongod"]
        args: ["--noprealloc", "--smallfiles", "--replSet", "rs4", "--dbpath","/data/db", "--auth",  "--keyFile", "/etc/secrets-volume/mongosecret", "--port", "27017", "--bind_ip_all"]
      volumes:
        - name: mongosh4-3
          persistentVolumeClaim:
           claimName: mongosh4-3
        - name: secrets-volume
          secret:
            secretName: mongosecret
            defaultMode: 256
